[game_menu]
grid_size = 8

[appearance.theme.light]
background = "FFFFFF"
foreground = "000000"
primary = "0000FF"
secondary = "00FF00"
tertiary = "FF0000"

[appearance.theme.dark]
foreground = "FFFFFF"
background = "000000"
primary = "0000FF"
secondary = "00FF00"
tertiary = "FF0000"